version: '3.7'

services:

  sample:
    container_name: cldev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 5000:5000
    environment:
      # So that hot-reloading will work:
      - CHOKIDAR_USEPOLLING=true